# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    database: POSTGRESQL
    show-sql: false
    
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/seido
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

jwt:
  header: Authorization
  secret: mySecret
  expiration: 10800
  route:
    authentication:
      path: auth
      refresh: refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG
